export { default as About } from "./components/about.svelte"
export { default as Affiliations } from "./components/affiliations.svelte"
export { default as Education } from "./components/education.svelte"
export { default as Employment } from "./components/employment.svelte"
export { default as Languages } from "./components/languages.svelte"
export { default as Publications } from "./components/publications.svelte"
export { default as Teaching } from "./components/teaching.svelte"
