export { default as About } from "./components/about.svelte"
export { default as Education } from "./components/education.svelte"
export { default as Employment } from "./components/employment.svelte"
export { default as Research } from "./components/research.svelte"
export { default as Teaching } from "./components/teaching.svelte"
